### ISSUE TITLE
第四節中的兩個問題

### ISSUE THREAD

**Issue by xieyuheng** [xieyuheng/the-tao-is-silent#2]
---

(1)

> By simple Aristotelian logic, we know that either God exists or he doesn’t, but we do not have confirming evidence one way or the other.

其中一部分 你翻譯成了

> 不管上帝存在與否，我們都沒有確切證據證明

我覺得 意思有誤 正確的意思是

> 上帝要麼存在 要麼不存在 只是我們沒有確切證據 來肯定其中之一

---

(2)

同一段中有一句

> “If there’s no meaning in it, that saves a world of trouble, as we needn’t try to find any”.

你翻譯成了

> “如果問題本身沒有意義可以免去不少麻煩的話，我們就不用費力去探尋什麼意義了。”

但是這個句子 首次出現其實是在前一篇 :: http://xieyuheng.github.io/the-tao-is-silent/part1-what-is-the-tao/3-does-the-tao-exist.html
在那裏 我把它翻譯成了

> 如果裏面沒有意義 那我們大家都省事兒了 我們也用不着找了

我覺得可以加一個 "因爲" (來自 "as" 一詞) 改成

> 如果裏面沒有意義 那我們大家都省事兒了 因爲我們就用不着找了

---

**Comment by waltlawrenceLL** [comment]
你看着改吧
我感觉你翻译的和我原来的意思都差不多
我前几天一直准备考试，也没用多少时间在翻译上，肯定有不到位的地方
